Repository prettier/prettier-eslint-cli, pull requests merged in 2022-08, with the labels that each got.

#439 BREAKING CHANGE: bump all upgradable (dev)Dependencies except pure ESM
  .nvmrc
Labels: breaking

#440 docs: cleanup build and sponsors badges
  README.md
Labels: breaking, documentation

#438 feat: make the cli work with/without `prettier-eslint` peer
  package.json
  src/format-files.js
  src/format-files.test.js
  src/prettier-eslint.js
  test/tests/cli.spec.js
Labels: enhancement, dependencies

#443 ci: migrate `semantic-release` to `changesets`
  .changeset/README.md
  .changeset/config.json
  .github/workflows/release.yml
  .nvmrc
  CONTRIBUTING.md
  README.md
  package.json
  test/tests/__snapshots__/cli.spec.js.snap
Labels: dependencies, internal

#288 fix(list-different): removed the message at the end of execution
  .all-contributorsrc
  .changeset/lovely-rings-cry.md
  README.md
  src/format-files.js
  src/format-files.test.js
  test/tests/__snapshots__/cli.spec.js.snap
Labels: bug

#132 feat: support matching dot files
  .all-contributorsrc
  .changeset/blue-parents-fail.md
  README.md
  src/format-files.js
  src/parser.js
Labels: enhancement
